 
---
spring: 
  profiles:
    active: local
    
              
server:
  port: 9003              

gallerySimplification:
  enabled: true 
  configPath: classpath:/divisionsConfiguration_local.json  
