---
xapi-static-data : 
    eventDivisions : 
        25 :
            banners: 
                - "albersons"
                - "vons"
                - "safeway"
            eventStartDateTime: "2020-01-01T00:00:00+00:00"
            eventEndDateTime: "2020-03-01T23:59:59+00:00"
        26 :
            banners: 
                - "safeway"
                - "albersons"
            eventStartDateTime: "2020-01-01T00:00:00+00:00"
            eventEndDateTime: "2020-12-31T23:59:59+00:00"
        29 :
            banners: 
                - "vons"
            eventStartDateTime: "2020-01-01T00:00:00+00:00"
            eventEndDateTime: "2020-12-31T23:59:59+00:00"
        33 :
            banners: 
                - "jewelosco"
            eventStartDateTime: "2020-01-01T00:00:00+00:00"
            eventEndDateTime: "2020-12-31T23:59:59+00:00"                   
