 
---
spring: 
  profiles:
    active: prod
    
              
kafka:
  producerEnabled: false

events:
  new_registration:
    enabled: true
    label: Welcome Offers
    minOffersValidityDays: 14
    stores: 535,9713
    includeStore: true
    registrationSource: sms, web, iOS, android, unknown, native-mobile, ABS-CEPS

gallerySimplification:
  enabled: false