 
---
spring: 
  profiles:
    active: acceptance
    
              
kafka: 
  producerEnabled: false   

gallerySimplification:
  enabled: false

events:
  new_registration:
    enabled: true
    label: Welcome Offers
    minOffersValidityDays: 14
    stores: 9611,9713,535,1118,3775,116,3088,3770,3073,122
    includeStore: true
    registrationSource: sms, web, iOS, android, unknown, native-mobile, ABS-CEPS          

